title: VizWit
baseurl: ''

defaults:
  - scope:
      path: pages
    values:
      layout: default
      permalink: /:basename/

prose:
  rooturl: pages
  siteurl: https://cityofphiladelphia.github.io/vizwit-pages/
  metadata:
    pages:
      - name: name
        field:
          element: text
          label: Name
      - name: description
        field:
          element: textarea
          label: Description
